//
//  AppCoordinator.swift
//  Editions Example App
//
//  Created by Luis Ángel San Martín Rodríguez on 04/11/2019.
//

import UIKit
import RichieEditionsSDK

public class AppCoordinator {
    private let window: UIWindow
    
    public init(window: UIWindow) {
        self.window = window
        let editions = Editions(bundleId: "fi.richie.editionsTestApp",
                                tokenProvider: TokenProviderImpl(),
                                analyticsListener: AnalyticsListenerImpl())
        
        self.window.rootViewController = LaunchViewController(nibName: "LaunchViewController", bundle: nil)

        self.window.makeKeyAndVisible()
        
        editions.initialize { success in
            if success {
                self.window.rootViewController = EditionsViewController(editions: editions)
            }
        }
    }
}

class TokenProviderImpl : TokenProvider {
    var hasToken: Bool { true }

    func token(reason: TokenRequestReason, trigger: TokenRequestTrigger, completion: @escaping TokenCompletion) {
        let jwtToken = "eyJhbGciOiJFUzM4NCIsImtpZCI6Im5JYVJ5d1RXNlg1WndPaXllWFNmeDhnYWVWV1d6Z2g4YkRVbUJSeVRseVUifQ.eyJpc3MiOiJodHRwczovL2FwcGRhdGEucmljaGllLmZpIiwiZW50IjpbImVkaXRpb25zX2RlbW9fY29udGVudCJdLCJleHAiOjE4OTA4ODkyMDAsImlhdCI6MTU3NTI3MDAwMH0.TWFZ6T8PqPwTB5Icv8BjxXiAVeZatoJxxSvTJcd31QXMnE-6m1_0XHELqv5Zr91Hg0XGyElo9HGhG7scTOlf17-40d35HnFn6cLoKrCJhGcrTNrUw1mJ7_W8X6XBeOZS"
        
        switch reason {
            
        case .noToken:
            // Here, the host app would get this JWT token from user login flow and return it to Richie SDK asynchronously.
            // For subsequent token requests, the host app would cache the token in memory for faster retrieval.
            // For demo purposes, we are using hardcoded JWT token generated by Richie.
            completion(jwtToken)
        case .noAccess:
            // Here, the host app would attempt to refresh the JWT token using app-specific auth backend.
            // This case is used if token provided in .noToken case was invalid or expired.
            Log.error("Current token is invalid.")
            completion(nil)
        case .noEntitlements:
            // Here, the host app would notify the user that he/she does not have enough entitlements for accessing the selected content.
            // This case is used if token provided in .noToken case was valid, but didn't provide enough entitlements for content.
            Log.error("Current token is not entitled to the selected content.")
            completion(nil)
        @unknown default:
            assertionFailure("Unknown token request reason: \(reason)")
            Log.error("Unknown token request reason: \(reason)")
            completion(nil)
        }
    }
}


class AnalyticsListenerImpl: AnalyticsListener {
    func onAnalyticsEvent(event: AnalyticsEvent) {
        Log.debug("Analytics event received: \(event.name) -> \(event.parameters)")
    }
}
